hydra:
  run:
    dir: ./outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}

seed: 42
data_root: "YOUR_DATASET_PATH"
start_iter: 0
total_iterations: 50000
checkpoint: null
batch_size: 4
image_size: 1024
ndf: 64
ngf: 64
nz: 256
lr: 0.0002
beta:
  beta_1: 0.5
  beta_2: 0.99
device: "cuda"
num_workers: 4
interval:
  save: 1000
  sample: 100
save_model_path: ""
policy: "color,translation"
